# Generated by Django 5.1.3 on 2024-11-26 15:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('CORP', 'Corporation'), ('LLC', 'Limited Liability Company'), ('PART', 'Partnership'), ('SOLE', 'Sole Proprietorship')], default='CORP', max_length=4)),
                ('website', models.URLField(blank=True)),
                ('established_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('position', models.CharField(choices=[('MGR', 'Manager'), ('DEV', 'Developer'), ('DES', 'Designer'), ('HR', 'HR'), ('SALES', 'Sales'), ('OTHER', 'Other')], default='OTHER', max_length=5)),
                ('hire_date', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('performance_rating', models.CharField(choices=[('EXC', 'Excellent'), ('GOOD', 'Good'), ('AVG', 'Average'), ('BELOW', 'Below Average'), ('POOR', 'Poor')], default='AVG', max_length=5)),
                ('projects_completed', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('email', 'company')},
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLAN', 'Planning'), ('PROG', 'In Progress'), ('COMP', 'Completed'), ('HOLD', 'On Hold')], default='PLAN', max_length=4)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('employees', models.ManyToManyField(related_name='projects', to='api.employee')),
            ],
        ),
    ]
