# Generated by Django 5.1.3 on 2024-11-26 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('about', models.TextField()),
                ('type', models.CharField(choices=[('IT', 'Information Technology'), ('NON_IT', 'Non IT'), ('MOBILE', 'Mobile Development'), ('WEB', 'Web Development'), ('AI', 'Artificial Intelligence'), ('DATA', 'Data Science')], max_length=20)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('employee_count', models.IntegerField(default=0)),
                ('website', models.URLField(blank=True, null=True)),
                ('founded_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('about', models.TextField()),
                ('position', models.CharField(choices=[('MANAGER', 'Manager'), ('DEVELOPER', 'Software Developer'), ('LEAD', 'Project Leader'), ('DESIGNER', 'UI/UX Designer'), ('ANALYST', 'Business Analyst'), ('DEVOPS', 'DevOps Engineer'), ('QA', 'Quality Assurance')], max_length=20)),
                ('hire_date', models.DateField(auto_now_add=True)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('performance_rating', models.CharField(choices=[('EXC', 'Excellent'), ('GOOD', 'Good'), ('AVG', 'Average'), ('BELOW', 'Below Average'), ('POOR', 'Poor')], default='AVG', max_length=5)),
                ('projects_completed', models.IntegerField(default=0)),
                ('skills', models.JSONField(default=dict)),
                ('last_review_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLAN', 'Planning'), ('PROG', 'In Progress'), ('TEST', 'Testing'), ('COMP', 'Completed'), ('HOLD', 'On Hold')], default='PLAN', max_length=4)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('technologies', models.JSONField(default=list)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('team_members', models.ManyToManyField(related_name='projects', to='api.employee')),
            ],
        ),
    ]
