# Generated by Django 5.1.3 on 2024-11-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_company_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='established_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
